from datetime import datetime


def get_demo_picker_data():
    """Genera los datos de picking demo con timestamps frescos."""
    now = datetime.utcnow().isoformat()
    return [
        {
            "picking_id": 1001,
            "pedido_id": 1001,
            "estado": "EN_PROCESO",
            "modo": "restaurant",
            "direccion_entrega": "Calle Mayor 12, Tarancón",
            "cliente_nombre": "Carlos Martínez",
            "cliente_telefono": "612345678",
            "total": 28.50,
            "iniciado_en": now,
            "items_total": 3,
            "items_listos": 0,
            "items_pendientes": 3,
            "picking_completo": False,
            "listo_para_finalizar": False,
            "items": [
                {
                    "item_id": 1,
                    "producto_id": 101,
                    "nombre": "Bocadillo de jamón",
                    "cantidad": 2,
                    "ubicacion": "A-1",
                    "imagen": None,
                    "estado": "pendiente",
                    "cantidad_encontrada": None,
                    "notas": None,
                },
                {
                    "item_id": 2,
                    "producto_id": 102,
                    "nombre": "Refresco lata",
                    "cantidad": 2,
                    "ubicacion": "B-3",
                    "imagen": None,
                    "estado": "pendiente",
                    "cantidad_encontrada": None,
                    "notas": None,
                },
                {
                    "item_id": 3,
                    "producto_id": 103,
                    "nombre": "Patatas fritas",
                    "cantidad": 1,
                    "ubicacion": "A-2",
                    "imagen": None,
                    "estado": "pendiente",
                    "cantidad_encontrada": None,
                    "notas": None,
                },
            ],
        },
        {
            "picking_id": 1002,
            "pedido_id": 1002,
            "estado": "EN_PROCESO",
            "modo": "restaurant",
            "direccion_entrega": "Av. Constitución 45, Tarancón",
            "cliente_nombre": "Ana López",
            "cliente_telefono": "698765432",
            "total": 19.90,
            "iniciado_en": now,
            "items_total": 2,
            "items_listos": 0,
            "items_pendientes": 2,
            "picking_completo": False,
            "listo_para_finalizar": False,
            "items": [
                {
                    "item_id": 4,
                    "producto_id": 104,
                    "nombre": "Menú del día completo",
                    "cantidad": 1,
                    "ubicacion": "C-1",
                    "imagen": None,
                    "estado": "pendiente",
                    "cantidad_encontrada": None,
                    "notas": None,
                },
                {
                    "item_id": 5,
                    "producto_id": 105,
                    "nombre": "Agua mineral",
                    "cantidad": 2,
                    "ubicacion": "B-1",
                    "imagen": None,
                    "estado": "pendiente",
                    "cantidad_encontrada": None,
                    "notas": None,
                },
            ],
        },
    ]


def get_demo_repartidor_data():
    """Genera los datos de reparto demo con timestamps frescos."""
    now = datetime.utcnow().isoformat()
    return [
        {
            "reparto_id": 2001,
            "pedido_id": 1001,
            "estado_reparto": "asignado",
            "estado_pedido": "PREPARADO",
            "cliente_nombre": "Carlos Martínez",
            "cliente_telefono": "612345678",
            "direccion_entrega": "Calle Mayor 12, Tarancón",
            "lat": 40.0053,
            "lng": -2.9956,
            "total": 28.50,
            "pago": {
                "estado": "cobrar_efectivo",
                "label": "Cobrar en efectivo",
                "importe": 28.50,
                "proveedor": None,
            },
            "items": [
                {"nombre": "Bocadillo de jamón", "cantidad": 2, "subtotal": 16.00},
                {"nombre": "Refresco lata", "cantidad": 2, "subtotal": 5.00},
                {"nombre": "Patatas fritas", "cantidad": 1, "subtotal": 7.50},
            ],
            "fecha_creacion": now,
            "hora_salida": None,
            "hora_estimada_entrega": None,
            "hora_entrega_real": None,
            "motivo_no_entrega": None,
            "notas": None,
        },
        {
            "reparto_id": 2002,
            "pedido_id": 1002,
            "estado_reparto": "asignado",
            "estado_pedido": "PREPARADO",
            "cliente_nombre": "Ana López",
            "cliente_telefono": "698765432",
            "direccion_entrega": "Av. Constitución 45, Tarancón",
            "lat": 40.0071,
            "lng": -2.9934,
            "total": 19.90,
            "pago": {
                "estado": "pagado_online",
                "label": "Pagado online",
                "importe": 19.90,
                "proveedor": "Monei",
            },
            "items": [
                {"nombre": "Menú del día completo", "cantidad": 1, "subtotal": 14.90},
                {"nombre": "Agua mineral", "cantidad": 2, "subtotal": 5.00},
            ],
            "fecha_creacion": now,
            "hora_salida": None,
            "hora_estimada_entrega": None,
            "hora_entrega_real": None,
            "motivo_no_entrega": None,
            "notas": None,
        },
    ]


def get_demo_cola_picker():
    """Genera la cola de pickings sin asignar."""
    now = datetime.utcnow().isoformat()
    return {
        "cola": [
            {
                "picking_id": 1003,
                "pedido_id": 1003,
                "estado": "EN_PROCESO",
                "modo": "restaurant",
                "direccion_entrega": "Calle Corta 5, Tarancón",
                "cliente_nombre": "María García",
                "cliente_telefono": "655123456",
                "total": 35.75,
                "iniciado_en": now,
                "items_total": 4,
                "items_listos": 0,
                "items_pendientes": 4,
                "picking_completo": False,
                "listo_para_finalizar": False,
                "items": [
                    {
                        "item_id": 6,
                        "producto_id": 106,
                        "nombre": "Sándwich mixto",
                        "cantidad": 2,
                        "ubicacion": "A-3",
                        "imagen": None,
                        "estado": "pendiente",
                        "cantidad_encontrada": None,
                        "notas": None,
                    },
                    {
                        "item_id": 7,
                        "producto_id": 107,
                        "nombre": "Zumo natural",
                        "cantidad": 2,
                        "ubicacion": "C-2",
                        "imagen": None,
                        "estado": "pendiente",
                        "cantidad_encontrada": None,
                        "notas": None,
                    },
                    {
                        "item_id": 8,
                        "producto_id": 108,
                        "nombre": "Ensalada",
                        "cantidad": 1,
                        "ubicacion": "B-2",
                        "imagen": None,
                        "estado": "pendiente",
                        "cantidad_encontrada": None,
                        "notas": None,
                    },
                    {
                        "item_id": 9,
                        "producto_id": 109,
                        "nombre": "Postre casero",
                        "cantidad": 1,
                        "ubicacion": "A-4",
                        "imagen": None,
                        "estado": "pendiente",
                        "cantidad_encontrada": None,
                        "notas": None,
                    },
                ],
            },
            {
                "picking_id": 1004,
                "pedido_id": 1004,
                "estado": "EN_PROCESO",
                "modo": "restaurant",
                "direccion_entrega": "Avenida Central 22, Tarancón",
                "cliente_nombre": "Roberto Sánchez",
                "cliente_telefono": "678456789",
                "total": 12.50,
                "iniciado_en": now,
                "items_total": 2,
                "items_listos": 0,
                "items_pendientes": 2,
                "picking_completo": False,
                "listo_para_finalizar": False,
                "items": [
                    {
                        "item_id": 10,
                        "producto_id": 110,
                        "nombre": "Tarta de chocolate",
                        "cantidad": 1,
                        "ubicacion": "C-3",
                        "imagen": None,
                        "estado": "pendiente",
                        "cantidad_encontrada": None,
                        "notas": None,
                    },
                    {
                        "item_id": 11,
                        "producto_id": 111,
                        "nombre": "Café",
                        "cantidad": 2,
                        "ubicacion": "B-4",
                        "imagen": None,
                        "estado": "pendiente",
                        "cantidad_encontrada": None,
                        "notas": None,
                    },
                ],
            },
        ],
        "total": 2,
    }


def get_demo_cola_repartidor():
    """Genera la cola de repartos sin asignar."""
    now = datetime.utcnow().isoformat()
    return {
        "cola": [
            {
                "reparto_id": 2003,
                "pedido_id": 1003,
                "estado_reparto": "asignado",
                "estado_pedido": "PREPARADO",
                "cliente_nombre": "María García",
                "cliente_telefono": "655123456",
                "direccion_entrega": "Calle Corta 5, Tarancón",
                "lat": 40.0045,
                "lng": -2.9970,
                "total": 35.75,
                "pago": {
                    "estado": "cobrar_efectivo",
                    "label": "Cobrar en efectivo",
                    "importe": 35.75,
                    "proveedor": None,
                },
                "items": [
                    {"nombre": "Sándwich mixto", "cantidad": 2, "subtotal": 14.00},
                    {"nombre": "Zumo natural", "cantidad": 2, "subtotal": 6.00},
                    {"nombre": "Ensalada", "cantidad": 1, "subtotal": 8.50},
                    {"nombre": "Postre casero", "cantidad": 1, "subtotal": 7.25},
                ],
                "fecha_creacion": now,
                "hora_salida": None,
                "hora_estimada_entrega": None,
                "hora_entrega_real": None,
                "motivo_no_entrega": None,
                "notas": None,
            },
            {
                "reparto_id": 2004,
                "pedido_id": 1004,
                "estado_reparto": "asignado",
                "estado_pedido": "PREPARADO",
                "cliente_nombre": "Roberto Sánchez",
                "cliente_telefono": "678456789",
                "direccion_entrega": "Avenida Central 22, Tarancón",
                "lat": 40.0062,
                "lng": -2.9945,
                "total": 12.50,
                "pago": {
                    "estado": "pagado_online",
                    "label": "Pagado online",
                    "importe": 12.50,
                    "proveedor": "Monei",
                },
                "items": [
                    {"nombre": "Tarta de chocolate", "cantidad": 1, "subtotal": 8.00},
                    {"nombre": "Café", "cantidad": 2, "subtotal": 4.50},
                ],
                "fecha_creacion": now,
                "hora_salida": None,
                "hora_estimada_entrega": None,
                "hora_entrega_real": None,
                "motivo_no_entrega": None,
                "notas": None,
            },
        ],
        "total": 2,
    }


DEMO_COLA_PICKER = get_demo_cola_picker()
DEMO_COLA_REPARTIDOR = get_demo_cola_repartidor()
